# Generated by Django 4.0.3 on 2022-04-18 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0002_alter_post_updated_alter_profile_banned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banned',
            field=models.ManyToManyField(blank=True, related_name='bans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ignored',
            field=models.ManyToManyField(blank=True, related_name='ignores', to=settings.AUTH_USER_MODEL),
        ),
    ]
